receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

processors:
  batch:
    timeout: 5s
  filter/ottl:
    error_mode: ignore
    logs:
      log_record:
        - 'instrumentation_scope.name != "Microsoft.AspNetCore.Hosting.Diagnostics"'
        - 'instrumentation_scope.name != "Microsoft.AspNetCore.Hosting.Diagnostics"'
        - 'instrumentation_scope.name != "Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker"'
        - 'instrumentation_scope.name != "Microsoft.Hosting.Lifetime"'

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]